export const SCHOOLS = [
  {
    id: "stoicism",
    name: "Stoicism",
    origin: "Ancient Greece & Rome",
    philosopher: "Marcus Aurelius · Epictetus",
    accentColor: "#C9A84C",
  },
  {
    id: "utilitarianism",
    name: "Utilitarianism",
    origin: "Western Modern",
    philosopher: "Jeremy Bentham · John Stuart Mill",
    accentColor: "#D4A96A",
  },
  {
    id: "existentialism",
    name: "Existentialism",
    origin: "Western Modern",
    philosopher: "Jean-Paul Sartre · Albert Camus",
    accentColor: "#D47B6A",
  },
  {
    id: "kantian",
    name: "Kantian Ethics",
    origin: "Western Modern",
    philosopher: "Immanuel Kant",
    accentColor: "#6A7ED4",
  },
  {
    id: "taoism",
    name: "Taoism",
    origin: "Ancient China",
    philosopher: "Laozi · Zhuangzi",
    accentColor: "#6BAD7A",
  },
  {
    id: "buddhism",
    name: "Buddhism",
    origin: "Ancient India & Asia",
    philosopher: "Siddhartha Gautama · Nagarjuna",
    accentColor: "#4CA8C9",
  },
  {
    id: "ubuntu",
    name: "Ubuntu",
    origin: "African Philosophy",
    philosopher: "Desmond Tutu · African Tradition",
    accentColor: "#D46A9D",
  },
  {
    id: "confucianism",
    name: "Confucianism",
    origin: "Ancient China",
    philosopher: "Confucius · Mencius",
    accentColor: "#6A8FD4",
  },
  {
    id: "nihilism",
    name: "Nihilism",
    origin: "Western Modern",
    philosopher: "Friedrich Nietzsche · Emil Cioran",
    accentColor: "#9A9A9A",
  },
  {
    id: "advaita",
    name: "Advaita Vedanta",
    origin: "Ancient India",
    philosopher: "Adi Shankaracharya · Ramana Maharshi",
    accentColor: "#9D6AD4",
  },
];
